/-
Copyright (c) 2026 Erdos 274 Agentic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erdos 274 Agentic contributors
-/
import Erdos274.Defs
import Mathlib.Algebra.GCDMonoid.FinsetLemmas
import Mathlib.Algebra.Group.Pointwise.Set.Card
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Data.Fintype.EquivFin
import Mathlib.Data.Nat.Cast.Field
import Mathlib.Data.Nat.Prime.Defs
import Mathlib.Data.Set.Card.Arithmetic
import Mathlib.Data.Set.Pairwise.Lattice
import Mathlib.GroupTheory.Coset.Card
import Mathlib.GroupTheory.CosetCover
import Mathlib.GroupTheory.GroupAction.Blocks
import Mathlib.GroupTheory.GroupAction.Primitive
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.PGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.SetTheory.Cardinal.Arithmetic
import Mathlib.Tactic.Linarith

universe u v

open scoped Cardinal Pointwise

namespace Erdos274

section ExactCovering

variable {G : Type u} [Group G] {ι : Type v} [Fintype ι]

namespace Group.ExactCovering

variable (P : Group.ExactCovering G ι)

theorem covers_finset :
    ⋃ i ∈ (Finset.univ : Finset ι), P.reps i • (P.parts i : Set G) = Set.univ := by
  simpa using P.covers

/-- Every coset in an exact covering is nonempty. -/
theorem coset_nonempty (i : ι) :
    (P.reps i • (P.parts i : Set G)).Nonempty := by
  exact ⟨P.reps i, ⟨1, (P.parts i).one_mem, mul_one _⟩⟩

/--
Every subgroup occurring in an exact finite coset partition has finite index.

Neumann's theorem says that the finite-index cosets alone still cover the group.  Exact
pairwise disjointness and nonemptiness then force every original coset to occur in that filtered
cover.
-/
theorem part_finiteIndex (i : ι) : (P.parts i).FiniteIndex := by
  classical
  let s : Finset ι := Finset.univ.filter fun j ↦ (P.parts j).FiniteIndex
  have hs_cover : ⋃ j ∈ s, P.reps j • (P.parts j : Set G) = Set.univ := by
    simpa [s] using
      (Subgroup.leftCoset_cover_filter_FiniteIndex (P.covers_finset))
  have hpairwise :
      ((Set.univ : Set ι) ∪ (s : Set ι)).PairwiseDisjoint
        (fun j ↦ P.reps j • (P.parts j : Set G)) := by
    simpa using P.disjoint
  have hsubset :
      (⋃ j ∈ (Set.univ : Set ι), P.reps j • (P.parts j : Set G)) ⊆
        ⋃ j ∈ (s : Set ι), P.reps j • (P.parts j : Set G) := by
    rw [show (⋃ j ∈ (Set.univ : Set ι),
        P.reps j • (P.parts j : Set G)) = Set.univ by simpa using P.covers]
    rw [Finset.set_biUnion_coe, hs_cover]
  have hi : i ∈ (s : Set ι) :=
    hpairwise.subset_of_biUnion_subset_biUnion
      (fun j _ ↦ P.coset_nonempty j) hsubset (Set.mem_univ i)
  simpa [s] using hi

/-- Every participating subgroup index is nonzero. -/
theorem part_index_ne_zero (i : ι) : (P.parts i).index ≠ 0 := by
  letI : (P.parts i).FiniteIndex := P.part_finiteIndex i
  exact Subgroup.FiniteIndex.index_ne_zero

/-- The intersection of all subgroups in the covering. -/
def commonIntersection : Subgroup G :=
  ⨅ i, P.parts i

/-- The subgroup generated by all subgroup parts of the covering. -/
def partsSup : Subgroup G :=
  ⨆ i, P.parts i

/-- The normal core of the common intersection. -/
def commonCore : Subgroup G :=
  P.commonIntersection.normalCore

instance commonCore_normal : P.commonCore.Normal := by
  change P.commonIntersection.normalCore.Normal
  exact Subgroup.normalCore_normal _

/-- The common intersection lies in every part. -/
theorem commonIntersection_le_part (i : ι) : P.commonIntersection ≤ P.parts i :=
  iInf_le _ i

/-- Every part lies in the subgroup generated by all parts. -/
theorem part_le_partsSup (i : ι) : P.parts i ≤ P.partsSup :=
  le_iSup (fun j ↦ P.parts j) i

/-- The common normal core lies in every part. -/
theorem commonCore_le_part (i : ι) : P.commonCore ≤ P.parts i :=
  (P.commonIntersection).normalCore_le.trans (P.commonIntersection_le_part i)

/-- If a subgroup lies in every participating subgroup except possibly one, exact placement forces
it to lie in the exceptional subgroup as well. -/
theorem subgroup_le_part_of_le_other_parts (k : ι) (K : Subgroup G)
    (hK : ∀ i, i ≠ k → K ≤ P.parts i) :
    K ≤ P.parts k := by
  intro z hzK
  have hcover : P.reps k * z ∈ ⋃ i, P.reps i • (P.parts i : Set G) := by
    rw [P.covers]
    exact Set.mem_univ _
  obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hcover
  have hik : i = k := by
    by_contra hik
    have hzi : z ∈ P.parts i := hK i hik hzK
    have hrep_i : P.reps k ∈ P.reps i • (P.parts i : Set G) := by
      rw [mem_leftCoset_iff] at hi ⊢
      have hmul := (P.parts i).mul_mem hi ((P.parts i).inv_mem hzi)
      have heq :
          (P.reps i)⁻¹ * (P.reps k * z) * z⁻¹ =
            (P.reps i)⁻¹ * P.reps k := by
        group
      rwa [heq] at hmul
    have hrep_k : P.reps k ∈ P.reps k • (P.parts k : Set G) := by
      rw [mem_leftCoset_iff]
      simp
    exact (Set.disjoint_left.mp
      (P.disjoint (Set.mem_univ i) (Set.mem_univ k) hik)) hrep_i hrep_k
  subst i
  rw [mem_leftCoset_iff] at hi
  simpa using hi

/-- Deleting any one part does not enlarge the common intersection of an exact coset cover. -/
theorem iInf_parts_ne_eq_commonIntersection (k : ι) :
    (⨅ i : {i // i ≠ k}, P.parts i.1) = P.commonIntersection := by
  have hk : (⨅ i : {i // i ≠ k}, P.parts i.1) ≤ P.parts k := by
    apply P.subgroup_le_part_of_le_other_parts
    intro i hik
    exact iInf_le_of_le ⟨i, hik⟩ le_rfl
  apply le_antisymm
  · apply le_iInf
    intro i
    by_cases hik : i = k
    · simpa only [hik] using hk
    · exact iInf_le_of_le ⟨i, hik⟩ le_rfl
  · apply le_iInf
    intro i
    exact P.commonIntersection_le_part i.1

/-- A finite intersection of the finite-index parts again has finite index. -/
theorem commonIntersection_finiteIndex : P.commonIntersection.FiniteIndex :=
  Subgroup.finiteIndex_iInf P.part_finiteIndex

/-- The normal core of the common intersection has finite index. -/
theorem commonCore_finiteIndex : P.commonCore.FiniteIndex := by
  letI : P.commonIntersection.FiniteIndex := P.commonIntersection_finiteIndex
  change P.commonIntersection.normalCore.FiniteIndex
  infer_instance

/-- The quotient by the common core is finite. -/
theorem finite_commonCore_quotient : Finite (G ⧸ P.commonCore) := by
  letI : P.commonCore.FiniteIndex := P.commonCore_finiteIndex
  infer_instance

/-- The left-coset action on the common-intersection quotient is finite. -/
theorem finite_commonIntersection_quotient : Finite (G ⧸ P.commonIntersection) := by
  letI : P.commonIntersection.FiniteIndex := P.commonIntersection_finiteIndex
  infer_instance

/-- A one-cell exact cover uses the whole ambient group as its part. -/
theorem part_eq_top_of_card_eq_one (hι : Fintype.card ι = 1) (i : ι) :
    P.parts i = ⊤ := by
  obtain ⟨i₀, hi₀⟩ := Fintype.card_eq_one_iff.mp hι
  have hcoset : P.reps i • (P.parts i : Set G) = Set.univ := by
    apply Set.eq_univ_iff_forall.mpr
    intro x
    have hx : x ∈ ⋃ j, P.reps j • (P.parts j : Set G) := by
      rw [P.covers]
      exact Set.mem_univ x
    obtain ⟨j, hxj⟩ := Set.mem_iUnion.mp hx
    simpa only [hi₀ i, hi₀ j] using hxj
  apply (Subgroup.eq_top_iff' _).mpr
  intro g
  have hg : P.reps i * g ∈ P.reps i • (P.parts i : Set G) := by
    rw [hcoset]
    exact Set.mem_univ _
  rw [mem_leftCoset_iff] at hg
  simpa using hg

/-- Every part in a nontrivial exact cover is a proper subgroup. -/
theorem part_ne_top_of_one_lt_card (hι : 1 < Fintype.card ι) (i : ι) :
    P.parts i ≠ ⊤ := by
  letI : Nontrivial ι := Fintype.one_lt_card_iff_nontrivial.mp hι
  obtain ⟨j, hji⟩ := exists_ne i
  obtain ⟨x, hxj⟩ := P.coset_nonempty j
  intro hi
  have hxi : x ∈ P.reps i • (P.parts i : Set G) := by
    rw [hi]
    simp
  exact (Set.disjoint_left.mp
    (P.disjoint (Set.mem_univ i) (Set.mem_univ j) hji.symm)) hxi hxj

end Group.ExactCovering

end ExactCovering

end Erdos274
