/-
Copyright (c) 2026 Murali Menon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Murali Menon
-/
module

public import Erdos274.KnownCases.Solvable.ExpWeight
public import Mathlib.Algebra.Order.Pi
public import Mathlib.Order.UpperLower.Closure


/-!
# Apexes, the 2/7 defect, and the charging lemma

`DECISION_LOG` D98 §§13–14.  Fix two coordinates `i ≠ j` and a shift length
`t ≥ 1`, and put `eᵢ = t·δᵢ`, `eⱼ = δⱼ`.  (At `p = 7`: `i` is the prime `2`,
`t = ord₇ 2 = 3`, and `j` is the prime `7`.)  Let `H₀` be an antichain (the
minimal heads) and `U = up H₀`.

* `defect U eᵢ eⱼ = ((U + eᵢ) ∩ (U + eⱼ)) ∖ (U + eᵢ + eⱼ)` is Sol's set `𝒟`.
  `W_shift_union_add_defect` is the exact inclusion–exclusion
  `W((U+eᵢ) ∪ (U+eⱼ)) + W(𝒟) + w(eᵢ)w(eⱼ)W(U) = (w(eᵢ) + w(eⱼ))W(U)`.
* The **apexes** of a minimal head `h` are `h + eⱼ` (the exact-7 point) and
  `h + eᵢ` (the exact-8 point).  `apex_notMem_shift_add` shows that neither
  lies in `U + eᵢ + eⱼ`.  Consequently an apex lies in `𝒟` as soon as it lies
  in the other shift (`apexJ_mem_defect`, `apexI_mem_defect`), and two
  coinciding apexes always do (`apex_eq_mem_defect`).
* **The charging lemma** (`charging`): the blocks `h + eⱼ + m·δᵢ`, `m < t`, of
  the exact-7 apexes in `𝒟` lie in `𝒟` and are pairwise disjoint, and they
  miss every exact-8 apex in `𝒟` that is not also an exact-7 apex.  Hence
  `β·W(Z₇ ∩ 𝒟) + W((Z₈ ∖ Z₇) ∩ 𝒟) ≤ W(𝒟)`, with `β = ∑_{m<t} rᵢ^m`.
* **Apexes are unusable** (`apexJ_of_part`, `apexI_of_part`): if a point
  `head + local`, with `head ∈ U` and `local` above `eⱼ` or `eᵢ`, equals an
  apex of `h`, then either it is the exact part at `h` itself or it lies
  in `𝒟`.

Everything here is order and arithmetic on `ι → ℕ`; the only group theory
enters later, as hypotheses.
-/

@[expose] public section

namespace Erdos274

namespace ApexCharging

open Set ExpWeight
open scoped ENNReal

variable {ι : Type*}

/-- The up-set generated by `H`: Mathlib's `upperClosure`, as a set. -/
abbrev up (H : Set (ι → ℕ)) : Set (ι → ℕ) := upperClosure H

theorem mem_up_of_mem {H : Set (ι → ℕ)} {h : ι → ℕ} (hh : h ∈ H) : h ∈ up H :=
  subset_upperClosure hh

/-- The up-set analogue of the finite union bound for a family of principal
upper sets. -/
theorem W_up_le [Fintype ι] {r : ι → ℝ≥0∞} (H₀ A : Finset (ι → ℕ)) :
    W r (up (H₀ : Set (ι → ℕ))) ≤ W r (up (A : Set (ι → ℕ))) +
      W r univ * ∑ h ∈ H₀ \ A, w r h := by
  classical
  have hsub : up (H₀ : Set (ι → ℕ)) ⊆ up (A : Set (ι → ℕ)) ∪ ⋃ h ∈ H₀ \ A, Ici h := by
    rintro z ⟨g, hg, hgz⟩
    by_cases hgA : g ∈ A
    · exact Or.inl ⟨g, hgA, hgz⟩
    · exact Or.inr (mem_iUnion₂.2 ⟨g, Finset.mem_sdiff.2 ⟨hg, hgA⟩, hgz⟩)
  calc W r (up (H₀ : Set (ι → ℕ)))
      ≤ W r (up (A : Set (ι → ℕ))) + W r (⋃ h ∈ H₀ \ A, Ici h) :=
        (W_mono hsub).trans (W_union_le _ _)
    _ ≤ W r (up (A : Set (ι → ℕ))) + ∑ h ∈ H₀ \ A, W r (Ici h) := by
        gcongr
        exact ExpWeight.W_biUnion_le r _ _
    _ = W r (up (A : Set (ι → ℕ))) + W r univ * ∑ h ∈ H₀ \ A, w r h := by
        rw [Finset.mul_sum]
        simp only [W_Ici, mul_comm]


/-- Sol's defect set `𝒟 = ((U + e) ∩ (U + f)) ∖ (U + e + f)`. -/
def defect (U : Set (ι → ℕ)) (e f : ι → ℕ) : Set (ι → ℕ) :=
  (shift e U ∩ shift f U) \ shift (e + f) U

/-! ### Shifts of up-sets -/

theorem mem_shift_up {e z : ι → ℕ} {H : Set (ι → ℕ)} :
    z ∈ shift e (up H) ↔ ∃ h ∈ H, h + e ≤ z := by
  rw [mem_shift]
  constructor
  · rintro ⟨hez, h, hH, hle⟩
    refine ⟨h, hH, fun k ↦ ?_⟩
    have h1 := hez k
    have h2 := hle k
    simp only [Pi.add_apply, Pi.sub_apply] at h1 h2 ⊢
    omega
  · rintro ⟨h, hH, hle⟩
    refine ⟨fun k ↦ ?_, h, hH, fun k ↦ ?_⟩ <;>
    · have h1 := hle k
      simp only [Pi.add_apply, Pi.sub_apply] at h1 ⊢
      omega

/-- A point `head + local` with `head ∈ up H` and `local ≥ e` lies in
`up H + e`. -/
theorem add_mem_shift_up {H : Set (ι → ℕ)} {hd l e : ι → ℕ} (hhd : hd ∈ up H)
    (hle : e ≤ l) : hd + l ∈ shift e (up H) := by
  obtain ⟨g, hg, hgd⟩ := hhd
  exact mem_shift_up.2 ⟨g, hg, add_le_add hgd hle⟩

theorem shift_mono_up {H : Set (ι → ℕ)} {e e' : ι → ℕ} (h : e ≤ e') :
    shift e' (up H) ⊆ shift e (up H) := fun _ hz ↦ by
  obtain ⟨g, hg, hle⟩ := mem_shift_up.1 hz
  exact mem_shift_up.2 ⟨g, hg, (add_le_add le_rfl h).trans hle⟩

/-! ### Apexes -/

variable [DecidableEq ι] {i j : ι} {t : ℕ}

/-- Neither apex of a minimal head lies in `U + eᵢ + eⱼ`. -/
theorem apex_notMem_shift_add {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h : ι → ℕ} (hh : h ∈ H₀) :
    h + Pi.single j 1 ∉ shift (Pi.single i t + Pi.single j 1) (up H₀) ∧
      h + Pi.single i t ∉ shift (Pi.single i t + Pi.single j 1) (up H₀) := by
  constructor <;>
  · intro hz
    obtain ⟨k, hk, hle⟩ := mem_shift_up.1 hz
    have hkh : k ≤ h := fun m ↦ by
      change k m ≤ h m
      have := hle m
      simp only [Pi.add_apply, Pi.single_apply] at this
      split_ifs at this <;> omega
    have hne : k ≠ h := by
      rintro rfl
      have hi := hle i
      have hj := hle j
      simp only [Pi.add_apply, Pi.single_eq_same, Pi.single_eq_of_ne hij,
        Pi.single_eq_of_ne hij.symm] at hi hj
      omega
    exact hH₀ hk hh hne hkh

/-- An exact-7 apex in `U + eᵢ` lies in `𝒟`. -/
theorem apexJ_mem_defect {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h : ι → ℕ} (hh : h ∈ H₀)
    (hi : h + Pi.single j 1 ∈ shift (Pi.single i t) (up H₀)) :
    h + Pi.single j 1 ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) :=
  ⟨⟨hi, add_mem_shift (mem_up_of_mem hh)⟩, (apex_notMem_shift_add hH₀ hij ht hh).1⟩

/-- An exact-8 apex in `U + eⱼ` lies in `𝒟`. -/
theorem apexI_mem_defect {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h : ι → ℕ} (hh : h ∈ H₀)
    (hj : h + Pi.single i t ∈ shift (Pi.single j 1) (up H₀)) :
    h + Pi.single i t ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) :=
  ⟨⟨add_mem_shift (mem_up_of_mem hh), hj⟩, (apex_notMem_shift_add hH₀ hij ht hh).2⟩

/-- A point that is both an exact-7 apex and an exact-8 apex lies in `𝒟`. -/
theorem apex_eq_mem_defect {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h h' : ι → ℕ} (hh : h ∈ H₀) (hh' : h' ∈ H₀)
    (heq : h + Pi.single j 1 = h' + Pi.single i t) :
    h + Pi.single j 1 ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) :=
  apexJ_mem_defect hH₀ hij ht hh (heq ▸ add_mem_shift (mem_up_of_mem hh'))

/-! ### Apexes are unusable -/

omit [DecidableEq ι] in
/-- An antichain head below `h`, together with a pointwise lower bound on its
increment, forces equality in both summands. -/
theorem eq_of_up_antichain_add_eq {H₀ : Set (ι → ℕ)}
    (hH₀ : IsAntichain (· ≤ ·) H₀) {h hd l e : ι → ℕ}
    (hh : h ∈ H₀) (hhd : hd ∈ up H₀) (hle : e ≤ l) (hpt : hd + l = h + e) :
    hd = h ∧ l = e := by
  have hle' : hd ≤ h := fun m ↦ by
    apply Nat.le_of_add_le_add_right
    calc
      hd m + e m ≤ hd m + l m := Nat.add_le_add_left (hle m) _
      _ = h m + e m := congrFun hpt m
  obtain ⟨g, hg, hgd⟩ := hhd
  have hgh : g = h := by
    by_contra hne
    exact hH₀ hg hh hne (hgd.trans hle')
  subst hgh
  have hdh : hd = g := le_antisymm hle' hgd
  subst hdh
  exact ⟨rfl, add_left_cancel hpt⟩

/-- **An exact-7 apex is used only by the exact part at its head, or lies in
`𝒟`.**  If `hd + l = h + eⱼ` with `hd ∈ U`, `h` minimal and `l ≥ eⱼ` or
`l ≥ eᵢ`, then either `hd = h` and `l = eⱼ`, or the point is in `𝒟`. -/
theorem apexJ_of_part {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h hd l : ι → ℕ} (hh : h ∈ H₀) (hhd : hd ∈ up H₀)
    (hl : Pi.single j 1 ≤ l ∨ Pi.single i t ≤ l) (hpt : hd + l = h + Pi.single j 1) :
    (hd = h ∧ l = Pi.single j 1) ∨
      h + Pi.single j 1 ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) := by
  rcases hl with hl | hl
  · left
    exact eq_of_up_antichain_add_eq hH₀ hh hhd hl hpt
  · right
    exact apexJ_mem_defect hH₀ hij ht hh (hpt ▸ add_mem_shift_up hhd hl)

/-- **An exact-8 apex is used only by the exact part at its head, or lies in
`𝒟`.** -/
theorem apexI_of_part {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) (ht : 1 ≤ t) {h hd l : ι → ℕ} (hh : h ∈ H₀) (hhd : hd ∈ up H₀)
    (hl : Pi.single j 1 ≤ l ∨ Pi.single i t ≤ l) (hpt : hd + l = h + Pi.single i t) :
    (hd = h ∧ l = Pi.single i t) ∨
      h + Pi.single i t ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) := by
  rcases hl with hl | hl
  · right
    exact apexI_mem_defect hH₀ hij ht hh (hpt ▸ add_mem_shift_up hhd hl)
  · left
    exact eq_of_up_antichain_add_eq hH₀ hh hhd hl hpt

/-! ### Blocks below an apex -/

omit [DecidableEq ι] in
theorem shift_up_isUpperSet (H : Set (ι → ℕ)) (e : ι → ℕ) : IsUpperSet (shift e (up H)) :=
  fun _ _ hab hz ↦ by
    obtain ⟨g, hg, hle⟩ := mem_shift_up.1 hz
    exact mem_shift_up.2 ⟨g, hg, hle.trans hab⟩

/-- Two minimal heads that differ by a move along coordinate `i` are equal, and
so are the moves. -/
theorem eq_of_add_single_eq {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    {h h' : ι → ℕ} (hh : h ∈ H₀) (hh' : h' ∈ H₀) {m m' : ℕ}
    (heq : h + Pi.single i m = h' + Pi.single i m') : h = h' ∧ m = m' := by
  have hc : ∀ k, h k + (Pi.single i m : ι → ℕ) k = h' k + (Pi.single i m' : ι → ℕ) k :=
    fun k ↦ by simpa only [Pi.add_apply] using congrFun heq k
  have hci : h i + m = h' i + m' := by simpa using hc i
  rcases le_total m m' with hmm | hmm
  · have hle : h' ≤ h := fun k ↦ by
      change h' k ≤ h k
      have := hc k
      simp only [Pi.single_apply] at this
      split_ifs at this <;> omega
    by_cases hne : h' = h
    · subst hne; exact ⟨rfl, by omega⟩
    · exact absurd hle (hH₀ hh' hh hne)
  · have hle : h ≤ h' := fun k ↦ by
      change h k ≤ h' k
      have := hc k
      simp only [Pi.single_apply] at this
      split_ifs at this <;> omega
    by_cases hne : h = h'
    · subst hne; exact ⟨rfl, by omega⟩
    · exact absurd hle (hH₀ hh hh' hne)

/-- **The block of an exact-7 apex lies in `𝒟`.**  If `h + eⱼ ∈ 𝒟` then so is
`h + eⱼ + m·δᵢ` for every `m < t`. -/
theorem block_mem_defect {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) {h : ι → ℕ} (hh : h ∈ H₀)
    (hD : h + Pi.single j 1 ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1))
    {m : ℕ} (hm : m < t) :
    h + Pi.single j 1 + Pi.single i m ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1) := by
  refine ⟨⟨shift_up_isUpperSet _ _ le_self_add hD.1.1, ?_⟩, ?_⟩
  · refine mem_shift_up.2 ⟨h, hh, fun k ↦ ?_⟩
    change h k + (Pi.single j 1 : ι → ℕ) k
      ≤ h k + (Pi.single j 1 : ι → ℕ) k + (Pi.single i m : ι → ℕ) k
    omega
  · intro hz
    obtain ⟨g, hg, hle⟩ := mem_shift_up.1 hz
    have hc : ∀ k, g k + ((Pi.single i t : ι → ℕ) k + (Pi.single j 1 : ι → ℕ) k)
        ≤ h k + (Pi.single j 1 : ι → ℕ) k + (Pi.single i m : ι → ℕ) k := fun k ↦ hle k
    have hgh : g ≤ h := fun k ↦ by
      change g k ≤ h k
      have := hc k
      simp only [Pi.single_apply] at this
      split_ifs at this <;> omega
    have hne : g ≠ h := by
      rintro rfl
      have := hc i
      simp only [Pi.single_eq_same, Pi.single_eq_of_ne hij] at this
      omega
    exact hH₀ hg hh hne hgh

/-- **A block misses the exact-8 apexes.**  If `h + eⱼ ∈ 𝒟`, `0 < m`, and
`h + eⱼ + m·δᵢ = h' + eᵢ` for a minimal `h'`, we have a contradiction: the
witness of `h + eⱼ ∈ U + eᵢ` would sit strictly below `h'`. -/
theorem block_ne_apexI {H₀ : Set (ι → ℕ)} (hH₀ : IsAntichain (· ≤ ·) H₀)
    (hij : i ≠ j) {h h' : ι → ℕ} (hh' : h' ∈ H₀)
    (hD : h + Pi.single j 1 ∈ defect (up H₀) (Pi.single i t) (Pi.single j 1))
    {m : ℕ} (hm0 : 0 < m) (heq : h + Pi.single j 1 + Pi.single i m = h' + Pi.single i t) :
    False := by
  obtain ⟨g, hg, hle⟩ := mem_shift_up.1 hD.1.1
  have hc : ∀ k, g k + (Pi.single i t : ι → ℕ) k ≤ h k + (Pi.single j 1 : ι → ℕ) k :=
    fun k ↦ hle k
  have he : ∀ k, h k + (Pi.single j 1 : ι → ℕ) k + (Pi.single i m : ι → ℕ) k
      = h' k + (Pi.single i t : ι → ℕ) k :=
    fun k ↦ by simpa only [Pi.add_apply] using congrFun heq k
  have hgh : g ≤ h' := fun k ↦ by
    change g k ≤ h' k
    have h1 := hc k
    have h2 := he k
    simp only [Pi.single_apply] at h1 h2
    split_ifs at h1 h2 <;> omega
  have hne : g ≠ h' := by
    rintro rfl
    have h1 := hc i
    have h2 := he i
    simp only [Pi.single_eq_same, Pi.single_eq_of_ne hij] at h1 h2
    omega
  exact hH₀ hg hh' hne hgh

/-! ### The exact inclusion–exclusion, and the charging lemma -/

variable [Fintype ι]

theorem w_single (r : ι → ℝ≥0∞) (i : ι) (m : ℕ) : w r (Pi.single i m) = r i ^ m := by
  rw [w, Finset.prod_eq_single i (fun k _ hk ↦ by simp [Pi.single_eq_of_ne hk])
    (by simp)]
  simp

omit [DecidableEq ι] in
/-- **`W((U+e) ∪ (U+f)) + W(𝒟) + w(e)w(f)W(U) = (w(e) + w(f))W(U)`**, for an
up-set generated by `H`.  This is Sol's identity `D₂₇ = (1/4)P − Pr(U ⊕ 𝓔₂₇)`
in reciprocal-mass form, with no truncation. -/
theorem W_shift_union_add_defect (r : ι → ℝ≥0∞) (H : Set (ι → ℕ)) (e f : ι → ℕ) :
    W r (shift e (up H) ∪ shift f (up H)) + W r (defect (up H) e f)
      + w r e * w r f * W r (up H) = (w r e + w r f) * W r (up H) := by
  have hsub : shift (e + f) (up H) ⊆ shift e (up H) ∩ shift f (up H) :=
    subset_inter (shift_mono_up le_self_add) (shift_mono_up le_add_self)
  have hinter : W r (shift e (up H) ∩ shift f (up H))
      = W r (shift (e + f) (up H)) + W r (defect (up H) e f) := by
    rw [defect, ← W_union_of_disjoint disjoint_sdiff_right, union_sdiff_cancel hsub]
  have h1 := W_union_add_inter (r := r) (shift e (up H)) (shift f (up H))
  rw [hinter, W_shift, W_shift, W_shift, w_add] at h1
  rw [add_mul, ← h1]
  ring

/-- **The charging lemma.**  Let `Z₇` be the exact-7 apexes of the minimal heads
outside `A`, and `Z₈` the exact-8 apexes of those outside `B`.  Every exact-7
apex in `𝒟` carries a whole block of `t` points of `𝒟`, of mass `β·w(apex)`
with `β = ∑_{m<t} rᵢ^m`; the blocks are disjoint, and they miss the exact-8
apexes in `𝒟` that are not exact-7 apexes.  So

    β·W(Z₇ ∩ 𝒟) + W((Z₈ ∖ Z₇) ∩ 𝒟) ≤ W(𝒟).

At `p = 7`, `β = 1 + 1/2 + 1/4 = 7/4`, which is Sol's constant. -/
theorem charging (r : ι → ℝ≥0∞) {H₀ A B : Finset (ι → ℕ)}
    (hH₀ : IsAntichain (· ≤ ·) (H₀ : Set (ι → ℕ))) (hij : i ≠ j) :
    (∑ m ∈ Finset.range t, r i ^ m)
        * W r (((H₀ \ A).image (· + Pi.single j 1) : Finset (ι → ℕ))
            ∩ defect (up H₀) (Pi.single i t) (Pi.single j 1))
      + W r ((((H₀ \ B).image (· + Pi.single i t) : Finset (ι → ℕ)) \
            ((H₀ \ A).image (· + Pi.single j 1) : Finset (ι → ℕ)))
            ∩ defect (up H₀) (Pi.single i t) (Pi.single j 1))
      ≤ W r (defect (up H₀) (Pi.single i t) (Pi.single j 1)) := by
  classical
  set D := defect (up (H₀ : Set (ι → ℕ))) (Pi.single i t) (Pi.single j 1) with hD
  set Z₇ := (H₀ \ A).image (· + Pi.single j 1) with hZ₇
  set Z₈ := (H₀ \ B).image (· + Pi.single i t) with hZ₈
  set X := Z₇.filter (· ∈ D) with hX
  set Y := (Z₈ \ Z₇).filter (· ∈ D) with hY
  set f : (ι → ℕ) × ℕ → ι → ℕ := fun p ↦ p.1 + Pi.single i p.2 with hf
  set Bl := (X ×ˢ Finset.range t).image f with hBl
  have hXcoe : (X : Set (ι → ℕ)) = (Z₇ : Set (ι → ℕ)) ∩ D := by
    ext x; simp [hX]
  have hYcoe : (Y : Set (ι → ℕ)) = ((Z₈ : Set (ι → ℕ)) \ Z₇) ∩ D := by
    ext x; simp [hY, and_assoc]
  have hXmem : ∀ x ∈ X, ∃ h ∈ H₀, x = h + Pi.single j 1 ∧ x ∈ D := by
    intro x hx
    obtain ⟨hxZ, hxD⟩ := Finset.mem_filter.1 hx
    obtain ⟨h, hh, rfl⟩ := Finset.mem_image.1 hxZ
    exact ⟨h, (Finset.mem_sdiff.1 hh).1, rfl, hxD⟩
  have hinj : Set.InjOn f (X ×ˢ Finset.range t : Finset _) := by
    rintro ⟨x, m⟩ hp ⟨x', m'⟩ hp' hfe
    simp only [Finset.coe_product, Set.mem_prod, Finset.mem_coe] at hp hp'
    obtain ⟨h, hh, rfl, -⟩ := hXmem x hp.1
    obtain ⟨h', hh', rfl, -⟩ := hXmem x' hp'.1
    have : h + Pi.single i m = h' + Pi.single i m' := by
      have := hfe
      simp only [hf] at this
      rw [add_right_comm, add_right_comm h'] at this
      exact add_right_cancel this
    obtain ⟨rfl, rfl⟩ := eq_of_add_single_eq hH₀ hh hh' this
    rfl
  have hBlD : (Bl : Set (ι → ℕ)) ⊆ D := by
    intro z hz
    obtain ⟨⟨x, m⟩, hp, rfl⟩ := Finset.mem_image.1 hz
    obtain ⟨hx, hm⟩ := Finset.mem_product.1 hp
    obtain ⟨h, hh, rfl, hxD⟩ := hXmem x hx
    exact block_mem_defect hH₀ hij hh hxD (Finset.mem_range.1 hm)
  have hdisj : Disjoint (Bl : Set (ι → ℕ)) (Y : Set (ι → ℕ)) := by
    rw [Set.disjoint_left]
    intro z hz hzY
    obtain ⟨⟨x, m⟩, hp, rfl⟩ := Finset.mem_image.1 hz
    obtain ⟨hx, hm⟩ := Finset.mem_product.1 hp
    obtain ⟨h, hh, rfl, hxD⟩ := hXmem x hx
    obtain ⟨hzZ, -⟩ := Finset.mem_filter.1 (Finset.mem_coe.1 hzY)
    obtain ⟨hz8, hz7⟩ := Finset.mem_sdiff.1 hzZ
    obtain ⟨h', hh', he⟩ := Finset.mem_image.1 hz8
    rcases Nat.eq_zero_or_pos m with rfl | hm0
    · apply hz7
      simp only [hf, Pi.single_zero, add_zero]
      exact (Finset.mem_filter.1 hx).1
    · exact block_ne_apexI hH₀ hij (Finset.mem_sdiff.1 hh').1 hxD hm0 he.symm
  have hWBl : W r (Bl : Set (ι → ℕ))
      = (∑ m ∈ Finset.range t, r i ^ m) * W r (X : Set (ι → ℕ)) := by
    rw [W_finset, W_finset, Finset.sum_image hinj, Finset.sum_product, Finset.mul_sum]
    refine Finset.sum_congr rfl fun x _ ↦ ?_
    simp only [hf, w_add, w_single, mul_comm, Finset.sum_mul]
  calc (∑ m ∈ Finset.range t, r i ^ m) * W r ((Z₇ : Set (ι → ℕ)) ∩ D)
        + W r (((Z₈ : Set (ι → ℕ)) \ Z₇) ∩ D)
      = W r (Bl : Set (ι → ℕ)) + W r (Y : Set (ι → ℕ)) := by rw [hWBl, hXcoe, hYcoe]
    _ = W r ((Bl : Set (ι → ℕ)) ∪ Y) := (W_union_of_disjoint hdisj).symm
    _ ≤ W r D := W_mono (Set.union_subset hBlD (by rw [hYcoe]; exact Set.inter_subset_right))


end ApexCharging

end Erdos274
