/-
Copyright (c) 2026 Murali Menon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Murali Menon
-/
import Erdos274.FiniteGroup.MinimalNormal
import Mathlib.GroupTheory.PGroup
import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.GroupAction.ConjAct
import Mathlib.GroupTheory.Solvable
import Mathlib.Algebra.Field.ZMod

/-!
# (CB), the cyclotomic block lemma

`SOLVABLE_HS_TRACK.md` §9.19 §3 (statement and paper proof due to OpenAI GPT-5.6
Sol).  This file proves it by working with a maximal subgroup of the whole group,
following `solvable-herzog-schonheim-review.md` §1; it needs neither primitive
permutation groups (Robinson 7.2.6) nor `GL(a,q)`.

> **(CB).**  Let `H` be a finite solvable group and `p` a prime, and suppose
> `H` has no nontrivial `p′`-quotient (`IsPResidual`).  If `Y < H` has
> `p ∤ [H : Y]`, then some prime `q ≠ p` dividing `|H|` has
> `q^{ord_p q} ∣ [H : Y]`.

* `orderOf_le_of_fixedPoints`: if a `p`-group acts nontrivially by
  automorphisms on a group of order `q^c`, with `q ≠ p`, then `ord_p q ≤ c`.
  The fixed points form a subgroup of order `q^b` with `b < c`, and
  `q^c ≡ q^b (mod p)` (`IsPGroup.card_modEq_card_fixedPoints`).
* `cyclotomic_block_index`.  Let `Q` be a Sylow `p`-subgroup.  A fixed point
  of `Q` on `H/Y` conjugates `Q` into `Y`.  Take `M ⊇ Y` a maximal subgroup,
  `N` its normal core, and `V` minimal among the normal subgroups with `N < V`.
  - `V/N` is minimal normal in the solvable group `H/N`, hence elementary
    abelian of exponent a prime `q` (`minimal_normal_is_elementary_abelian`).
  - `V ⊄ M`, so `M ⊔ V = H` and `[H : M] = [V : V ⊓ M]`, a power of `q`.
  - `Q ≤ M` acts on `A = V/(V ⊓ M)` by conjugation, nontrivially: otherwise
    `vxv⁻¹ ∈ M` for `x ∈ Q`, `v ∈ V`, so `Q ≤ N` (as `H = MV`); then `N`
    is normal of `p′`-index, so `N = H` by `IsPResidual`, contradicting `N ≤ M`.
  - `q ∣ [H : M] ∣ |H|`, and `q ≠ p` because `[H : M] ∣ [H : Y]`.
-/

namespace Erdos274

namespace CyclotomicBlock

open MulAction
open scoped Pointwise

universe u

/-! ### The fixed-point count -/

/-- **A `p`-group acting nontrivially on a group of order `q^c` forces
`ord_p q ≤ c`.** -/
theorem orderOf_le_of_fixedPoints {p q c : ℕ} [hp : Fact p.Prime] (hq : q.Prime)
    (hpq : p ≠ q) {P A : Type*} [Group P] [Group A] [Finite A]
    [MulDistribMulAction P A]
    (hP : IsPGroup p P) (hA : Nat.card A = q ^ c) (hnt : ∃ (x : P) (a : A), x • a ≠ a) :
    orderOf (q : ZMod p) ≤ c := by
  set Fx := FixedPoints.subgroup P A
  obtain ⟨b, hbc, hb⟩ : ∃ b ≤ c, Nat.card Fx = q ^ b :=
    (Nat.dvd_prime_pow hq).mp (hA ▸ Subgroup.card_subgroup_dvd_card Fx)
  have hbne : b ≠ c := by
    rintro rfl
    obtain ⟨x, a, hxa⟩ := hnt
    have htop : Fx = ⊤ := Subgroup.eq_top_of_card_eq Fx (hb.trans hA.symm)
    have hmem : a ∈ Fx := by rw [htop]; exact Subgroup.mem_top a
    exact hxa ((FixedPoints.mem_subgroup P A a).mp hmem x)
  have hmod := hP.card_modEq_card_fixedPoints A
  have hfix : Nat.card (fixedPoints P A) = Nat.card Fx := rfl
  rw [hfix, hb, hA] at hmod
  have hZ : ((q : ZMod p)) ^ c = (q : ZMod p) ^ b := by
    exact_mod_cast (ZMod.natCast_eq_natCast_iff _ _ _).mpr hmod
  have hq0 : (q : ZMod p) ≠ 0 := by
    rw [Ne, ZMod.natCast_eq_zero_iff]
    intro h
    exact hpq ((Nat.prime_dvd_prime_iff_eq hp.out hq).mp h)
  have hone : (q : ZMod p) ^ (c - b) = 1 := by
    have h := hZ
    rw [← Nat.sub_add_cancel hbc, pow_add] at h
    exact (mul_eq_right₀ (pow_ne_zero _ hq0)).mp h
  have hdvd := orderOf_dvd_of_pow_eq_one hone
  have hpos : 0 < c - b := by omega
  exact (Nat.le_of_dvd hpos hdvd).trans (Nat.sub_le c b)

/-! ### Index arithmetic -/

variable {H : Type u} [Group H]

/-- `[M ⊔ V : M] = [V : M ⊓ V]` for `V` normal. -/
theorem relIndex_sup_normal [Finite H] (M V : Subgroup H) [V.Normal] :
    M.relIndex (M ⊔ V) = (M ⊓ V).relIndex V := by
  have h1 := Subgroup.relIndex_mul_relIndex (M ⊓ V) M (M ⊔ V) inf_le_left le_sup_left
  have h2 := Subgroup.relIndex_mul_relIndex (M ⊓ V) V (M ⊔ V) inf_le_right le_sup_right
  have h3 : V.relIndex (M ⊔ V) = (M ⊓ V).relIndex M := by
    rw [Subgroup.relIndex_sup_right, ← Subgroup.inf_relIndex_right V M, inf_comm]
  rw [h3, ← h1, mul_comm] at h2
  have h0 : (M ⊓ V).relIndex M ≠ 0 := ((M ⊓ V).subgroupOf M).index_ne_zero_of_finite
  exact (Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero h0) h2).symm

/-- Conjugating by an element of the normaliser keeps a subgroup's elements in it. -/
theorem conj_mem_of_mem_normalizer {X : Subgroup H} {x y : H}
    (hx : x ∈ Subgroup.normalizer (X : Set H)) (hy : y ∈ X) : x * y * x⁻¹ ∈ X :=
  (Subgroup.mem_normalizer_iff.mp hx y).mp hy

/-- **`H` has no nontrivial `p′`-quotient**: every normal subgroup of index
prime to `p` is all of `H`.  Equivalently `H = O^{p′}(H)`, the subgroup
generated by the `p`-elements. -/
def IsPResidual (p : ℕ) (H : Type*) [Group H] : Prop :=
  ∀ N : Subgroup H, N.Normal → ¬ p ∣ N.index → N = ⊤

section Core

variable [Finite H]

/-- **A `p`-group conjugates into a subgroup of `p′`-index**: `Q` fixes a point
`gY` of `H/Y`, since `p ∤ |H/Y|`, and then `g⁻¹Qg ≤ Y`. -/
theorem exists_conj_mem_of_not_dvd {p : ℕ} [Fact p.Prime] {Q Y : Subgroup H}
    (hQ : IsPGroup p Q) (hpY : ¬ p ∣ Y.index) : ∃ g : H, ∀ x ∈ Q, g⁻¹ * x * g ∈ Y := by
  classical
  obtain ⟨c, hc⟩ : (fixedPoints Q (H ⧸ Y)).Nonempty := by
    by_contra hne
    rw [Set.not_nonempty_iff_eq_empty] at hne
    have hmod := hQ.card_modEq_card_fixedPoints (H ⧸ Y)
    rw [hne] at hmod
    simp only [Nat.card_of_isEmpty] at hmod
    exact hpY ((Nat.modEq_zero_iff_dvd).mp hmod)
  obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective c
  refine ⟨g, fun x hx ↦ ?_⟩
  have h := hc ⟨x⁻¹, Q.inv_mem hx⟩
  rw [Subgroup.smul_def, MulAction.Quotient.smul_mk, smul_eq_mul, QuotientGroup.eq] at h
  simpa [mul_assoc] using h

/-- **(CB), the cyclotomic block lemma, in index form.**  If `H` is solvable
with no nontrivial `p′`-quotient and `Y < H` has `p ∤ [H : Y]`, then some
prime `q ≠ p` dividing `|H|` has `q^{ord_p q} ∣ [H : Y]`. -/
theorem cyclotomic_block_index [Group.IsSolvable H] {p : ℕ} [Fact p.Prime]
    (hres : IsPResidual p H) {Y : Subgroup H} (hY : Y ≠ ⊤) (hpY : ¬ p ∣ Y.index) :
    ∃ q, q.Prime ∧ q ≠ p ∧ q ∣ Nat.card H ∧ q ^ orderOf (q : ZMod p) ∣ Y.index := by
  classical
  have : Finite (Subgroup H) :=
    Finite.of_injective (fun S : Subgroup H ↦ (S : Set H)) SetLike.coe_injective
  -- `Q`: a Sylow `p`-subgroup of `H`
  obtain ⟨P⟩ : Nonempty (Sylow p H) := inferInstance
  set Q : Subgroup H := (P : Subgroup H) with hQdef
  have hQ : IsPGroup p Q := P.isPGroup'
  have hQidx : ¬ p ∣ Q.index := P.not_dvd_index
  obtain ⟨g, hgx⟩ := exists_conj_mem_of_not_dvd hQ hpY
  -- conjugate `Y` so that it contains `Q`
  set Y₁ := Y.map ((MulAut.conj g : H ≃* H) : H →* H) with hY₁
  have hidx : Y₁.index = Y.index := Subgroup.index_map_equiv Y (MulAut.conj g)
  have hQY : Q ≤ Y₁ := by
    intro x hx
    refine ⟨g⁻¹ * x * g, hgx x hx, ?_⟩
    change g * (g⁻¹ * x * g) * g⁻¹ = x
    group
  have hY₁ : Y₁ ≠ ⊤ := by
    intro h
    apply hY
    rw [← Subgroup.index_eq_one, ← hidx, h, Subgroup.index_top]
  -- `M`: a maximal subgroup above `Y₁`
  obtain ⟨M, hYM, hMmax⟩ := Finite.exists_le_maximal
    (p := fun M : Subgroup H ↦ Y₁ ≤ M ∧ M ≠ ⊤) ⟨le_rfl, hY₁⟩
  obtain ⟨-, hMne⟩ := hMmax.prop
  have hQM : Q ≤ M := hQY.trans hYM
  have hMQ : Q ≤ Subgroup.normalizer (M : Set H) := hQM.trans Subgroup.le_normalizer
  have hMY : M.index ∣ Y.index := hidx ▸ Subgroup.index_dvd_of_le hYM
  -- `N`: the normal core of `M`
  set N := M.normalCore with hNdef
  have hNM : N ≤ M := M.normalCore_le
  -- `V`: minimal among the normal subgroups with `N < V`
  let S : Set (Subgroup H) := {V | V.Normal ∧ N < V}
  have hTS : ⊤ ∈ S := ⟨inferInstance, lt_of_le_of_ne le_top
    (fun h ↦ hMne (top_le_iff.mp (h ▸ hNM)))⟩
  obtain ⟨V, -, hVmin⟩ := (Set.toFinite S).isPWO.exists_le_minimal hTS
  obtain ⟨hVn, hNV⟩ := hVmin.prop
  -- `V/N` is a minimal normal section, hence elementary abelian
  obtain ⟨q, hq, hexpV, hcommV⟩ := exists_prime_of_minimal_normal_section hVn hNV
    fun V' hV'n hNV' hV'V ↦ le_antisymm hV'V (hVmin.2 ⟨hV'n, hNV'⟩ hV'V)
  have : Fact q.Prime := ⟨hq⟩
  have hconjM : ∀ v ∈ V, ∀ d ∈ V ⊓ M, v * d * v⁻¹ ∈ M := by
    intro v hv d hd
    have hvd : ((v : H ⧸ N)) * d = d * v := hcommV v hv d hd.1
    have h : ((v * d * v⁻¹ : H) : H ⧸ N) = d := by
      simp only [QuotientGroup.mk_mul, QuotientGroup.mk_inv, hvd, mul_inv_cancel_right]
    have hn : (v * d * v⁻¹)⁻¹ * d ∈ N := QuotientGroup.eq.mp h
    have e : v * d * v⁻¹ = d * ((v * d * v⁻¹)⁻¹ * d)⁻¹ := by group
    rw [e]
    exact M.mul_mem hd.2 (M.inv_mem (hNM hn))
  -- `M ⊔ V = H`
  have hVM : ¬ V ≤ M := fun h ↦ hNV.not_ge (Subgroup.normal_le_normalCore.mpr h)
  have hsupMV : M ⊔ V = ⊤ := by
    by_contra hne
    exact hVM ((hMmax.2 ⟨hYM.trans le_sup_left, hne⟩ le_sup_left).trans' le_sup_right)
  -- the quotient `A = V/(V ⊓ M)`, of order `[H : M]`
  set D' := (V ⊓ M).subgroupOf V with hD'
  have hD'n : D'.Normal := ⟨fun n hn g ↦ by
    rw [hD', Subgroup.mem_subgroupOf] at hn ⊢
    exact ⟨(g * n * g⁻¹).2, hconjM g g.2 n hn⟩⟩
  have hcardA : Nat.card (V ⧸ D') = M.index := by
    rw [← Subgroup.relIndex_top_right, ← hsupMV, relIndex_sup_normal, inf_comm]
    rfl
  -- the action of `Q` on `A` by conjugation
  have hmapD : ∀ x : Q, D'.map (MulAut.conjNormal (x : H) : V ≃* V).toMonoidHom = D' := by
    intro x
    have hin : ∀ y : Q, ∀ z : V, z ∈ D' → MulAut.conjNormal (y : H) z ∈ D' := by
      intro y z hz
      rw [hD', Subgroup.mem_subgroupOf] at hz ⊢
      rw [MulAut.conjNormal_apply]
      exact ⟨Subgroup.Normal.conj_mem inferInstance _ z.2 _,
        conj_mem_of_mem_normalizer (hMQ y.2) hz.2⟩
    refine le_antisymm ?_ fun z hz ↦ ?_
    · rintro _ ⟨z, hz, rfl⟩
      exact hin x z hz
    · refine ⟨(MulAut.conjNormal (x : H))⁻¹ z, ?_, by simp⟩
      have := hin x⁻¹ z hz
      simpa using this
  let φ : Q →* MulAut (V ⧸ D') :=
    { toFun := fun x ↦ QuotientGroup.congr D' D' (MulAut.conjNormal (x : H)) (hmapD x)
      map_one' := by
        ext a
        induction a using QuotientGroup.induction_on
        simp [QuotientGroup.congr_mk]
      map_mul' := by
        intro x y
        ext a
        induction a using QuotientGroup.induction_on
        simp only [QuotientGroup.congr_mk, MulAut.mul_apply, Subgroup.coe_mul, map_mul]
        rfl }
  let _ : MulDistribMulAction Q (V ⧸ D') := MulDistribMulAction.compHom _ φ
  have hsmul : ∀ (x : Q) (v : V), x • ((v : V ⧸ D')) =
      ((MulAut.conjNormal (x : H) v : V) : V ⧸ D') := fun x v ↦ rfl
  -- the action is nontrivial: otherwise `Q` lies in the normal core of `M`,
  -- a normal subgroup of `p′`-index, which is then all of `H`
  have hnt : ∃ (x : Q) (a : V ⧸ D'), x • a ≠ a := by
    by_contra hall
    push Not at hall
    have hfix : ∀ x ∈ Q, ∀ v ∈ V, x * v * x⁻¹ * v⁻¹ ∈ M := by
      intro x hx v hv
      have h := hall ⟨x, hx⟩ ((⟨v⁻¹, V.inv_mem hv⟩ : V) : V ⧸ D')
      rw [hsmul, QuotientGroup.eq, hD', Subgroup.mem_subgroupOf] at h
      have h2 := h.2
      simp only [Subgroup.coe_mul, Subgroup.coe_inv, MulAut.conjNormal_apply] at h2
      have e : x * v * x⁻¹ * v⁻¹ = (x * v⁻¹ * x⁻¹)⁻¹ * v⁻¹ := by group
      rw [e]
      exact h2
    have hcore : Q ≤ M.normalCore := by
      intro x hx b
      have hb : b ∈ ((M ⊔ V : Subgroup H) : Set H) := hsupMV ▸ Subgroup.mem_top b
      rw [Subgroup.mul_normal M V] at hb
      obtain ⟨m, hm, v, hv, rfl⟩ := hb
      have hvx : v * x * v⁻¹ ∈ M := by
        have e : v * x * v⁻¹ = x * (x⁻¹ * v * x⁻¹⁻¹ * v⁻¹) := by group
        rw [e]
        exact M.mul_mem (hQM hx) (hfix x⁻¹ (Q.inv_mem hx) v hv)
      have e : m * v * x * (m * v)⁻¹ = m * (v * x * v⁻¹) * m⁻¹ := by group
      rw [e]
      exact M.mul_mem (M.mul_mem hm hvx) (M.inv_mem hm)
    have hcore_top : M.normalCore = ⊤ :=
      hres _ inferInstance fun h ↦ hQidx (h.trans (Subgroup.index_dvd_of_le hcore))
    exact hMne (top_le_iff.mp (hcore_top ▸ M.normalCore_le))
  -- `A` is a `q`-group
  have hAq : IsPGroup q (V ⧸ D') := by
    intro a
    induction a using QuotientGroup.induction_on with
    | H v =>
      refine ⟨1, ?_⟩
      rw [pow_one, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff, hD',
        Subgroup.mem_subgroupOf]
      exact ⟨(v ^ q).2, hNM (by simpa using hexpV v v.2)⟩
  obtain ⟨c, hc⟩ := IsPGroup.iff_card.mp hAq
  have hc0 : c ≠ 0 := by
    rintro rfl
    obtain ⟨x, a, hxa⟩ := hnt
    rw [pow_zero] at hc
    have : Subsingleton (V ⧸ D') := (Nat.card_eq_one_iff_unique.mp hc).1
    exact hxa (Subsingleton.elim _ _)
  have hqM : q ∣ M.index := by
    rw [← hcardA, hc]
    exact dvd_pow_self q hc0
  -- `q ≠ p`, as `[H : M] ∣ [H : Y]`
  have hpq : p ≠ q := fun h ↦ hpY (by rw [h]; exact hqM.trans hMY)
  have hord := orderOf_le_of_fixedPoints hq hpq hQ hc hnt
  refine ⟨q, hq, hpq.symm, hqM.trans M.index_dvd_card, ?_⟩
  calc q ^ orderOf (q : ZMod p) ∣ q ^ c := pow_dvd_pow q hord
    _ = M.index := hc.symm.trans hcardA
    _ ∣ Y.index := hMY

end Core

end CyclotomicBlock

end Erdos274
