/-
Copyright (c) 2026 Murali Menon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Murali Menon
-/
module

public import Erdos274.KnownCases.Solvable.CyclotomicBlock
public import Mathlib.GroupTheory.Sylow


/-!
# The step-4 localisation `F = O^{p′}(G)`

`solvable-herzog-schonheim-review.md` §1, stage 2.  Let `G` be a finite group
and `p` a prime dividing `|G|`.  Put `F` = the normal closure of a Sylow
`p`-subgroup `P`, i.e. `O^{p′}(G)`, the subgroup generated by the
`p`-elements.  Then
* `F ◁ G` and `F ≠ 1`;
* `F` has no nontrivial `p′`-quotient (`CyclotomicBlock.IsPResidual`).

For the last: let `N ◁ F` have index prime to `p`.  Each conjugate `gPg⁻¹` is a
`p`-subgroup of `F`, so its image in the `p′`-group `F/N` is trivial and
`gPg⁻¹ ≤ N`.  These conjugates generate `F`.

This replaces the earlier construction `F = KQ` with `K = [O_{p′}(G), Q]`, which
needed the coprime-action identity `N = [N,Q]·C_N(Q)` and the Frattini argument.
No solvability is used here.
-/

@[expose] public section

namespace Erdos274

namespace Step4Structure

open CyclotomicBlock

universe u

variable {G : Type u} [Group G] [Finite G]

/-- **A `p`-subgroup lies in every normal subgroup of `p′`-index.** -/
theorem le_of_isPGroup_of_not_dvd_index {p : ℕ} [hp : Fact p.Prime] {T N : Subgroup G}
    [N.Normal] (hT : IsPGroup p T) (hN : ¬ p ∣ N.index) : T ≤ N := by
  have hTm : IsPGroup p (T.map (QuotientGroup.mk' N)) := hT.map _
  obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp hTm
  have hdvd : Nat.card (T.map (QuotientGroup.mk' N)) ∣ N.index :=
    Subgroup.card_subgroup_dvd_card _
  rcases k with _ | k
  · rw [pow_zero] at hk
    rw [← QuotientGroup.ker_mk' N, ← Subgroup.map_eq_bot_iff]
    exact Subgroup.eq_bot_of_card_eq _ hk
  · exact absurd ((dvd_pow_self p (Nat.succ_ne_zero k)).trans (hk ▸ hdvd)) hN

/-- **The step-4 structure.**  For a prime `p ∣ |G|` there is `F ◁ G`, `F ≠ 1`,
with no nontrivial `p′`-quotient. -/
theorem exists_structure {p : ℕ} [hp : Fact p.Prime] (hpG : p ∣ Nat.card G) :
    ∃ F : Subgroup G, F.Normal ∧ F ≠ ⊥ ∧ IsPResidual p F := by
  obtain ⟨P⟩ : Nonempty (Sylow p G) := inferInstance
  set F := Subgroup.normalClosure ((P : Subgroup G) : Set G) with hFdef
  have hPF : (P : Subgroup G) ≤ F := Subgroup.subset_normalClosure
  refine ⟨F, inferInstance, fun h ↦ P.ne_bot_of_dvd_card hpG (eq_bot_iff.mpr (h ▸ hPF)), ?_⟩
  intro N hNn hN
  -- every conjugate of `P` lies in `N`
  have hconj : Group.conjugatesOfSet ((P : Subgroup G) : Set G) ⊆ N.map F.subtype := by
    intro y hy
    obtain ⟨x, hx, hxy⟩ := Group.mem_conjugatesOfSet_iff.mp hy
    obtain ⟨c, rfl⟩ := isConj_iff.mp hxy
    have hyF : c * x * c⁻¹ ∈ F :=
      Subgroup.normalClosure_normal.conj_mem x (hPF hx) c
    set T : Subgroup F := ((P : Subgroup G).map (MulAut.conj c).toMonoidHom).subgroupOf F
    have hT : IsPGroup p T :=
      (P.isPGroup'.map _).comap_of_injective F.subtype F.subtype_injective
    have hmem : (⟨c * x * c⁻¹, hyF⟩ : F) ∈ T := by
      rw [Subgroup.mem_subgroupOf]
      exact ⟨x, hx, rfl⟩
    exact ⟨_, le_of_isPGroup_of_not_dvd_index hT hN hmem, rfl⟩
  have hFN : F ≤ N.map F.subtype := (Subgroup.closure_le _).mpr hconj
  refine eq_top_iff.mpr fun z _ ↦ ?_
  obtain ⟨w, hw, hwz⟩ := hFN z.2
  rwa [Subtype.ext hwz] at hw

end Step4Structure

end Erdos274
